[package]
name = "mqtt-fri"
version = "0.1.0"
authors = ["Netz <Netz@home>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }
rumqttc = "0.6"
