name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - 'rust/**'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build hello
      working-directory: ./rust/hello
      run: cargo build --verbose
    - name: Run tests hello
      working-directory: ./rust/hello
      run: cargo test --verbose
    - name: Build mqtt
      working-directory: ./rust/mqtt-fri
      run: cargo build --verbose
